---
title: "Assignment09"
author: "Erin Keller"
date: "March 22, 2017"
output: html_document
---
# Linear Regression
```{r}
#################################################
# Function: FitLinear
# Outputs summary statistics of linear regression for a given data frame
# Input: dataframe, x values in first column, y values in second column
# Output: r-squared value, slope, and pvalue

FitLinear <- function(data=cbind(runif(10),runif(10))) {
  x <- data[,1]
  y <- data[,2]
  dataFrame <- data.frame(x,y)

  regModel <- lm(y~x,data=dataFrame)
  
  myOut<- c(slope = summary(regModel)$coefficients[2,1],
            pvalue = summary(regModel)$coefficients[2,4],
            Rsquared = summary(regModel)$adj.r.squared)
            
  
  return(myOut)
}
#######################################################
```
```{r}
data <- read.table("Victoria.csv",header=TRUE,sep=",")
Var10 <- data[,10]
str(Var10)
str(Var7)
Var7 <- data[,7]
Model710 <- cbind(Var7,Var10)
Model710
str(Model710)
FitLinear(Model710)
PlotLinear(
```



# Contingency Table
```{r}
###################################################
# Function: ContTable
# Reports the results from the Chi Squared analysis for a given data frame
# Inputs: discrete numerical vectors for both
# Outputs: the results from the Chi Square analysis

ContTable <- function(data=cbind(runif(10),runif(10))) {
  x <- data[,1]
  y <- data[,2]
  dataFrame <- data.frame(x,y)
  
  print(chisq.test(dataFrame))

}
ContTable()
```
# ANOVA
```{r}
# Function: AnovaData
# Reports F value (test statistic for the variation between sample means) for a given data frame
# Inputs: continuous numeric vector for x and a discrete vector for y
# Outputs: a mosaic plot with p-value and a bar plot

AnovaData <- function(data=cbind(runif(10),runif(10))) {
  x <- data[,1]
  y <- data[,2]
  dataFrame <- data.frame(x,y)

 AnovaModel<- aov(y~x,data=dataFrame)
  
  print(summary(AnovaModel))

}
data<- read.table("SporCount.csv",header=TRUE,sep=",")
data1 <- data[,1:2]

head(data1)
AnovaData(data=data1)
```
```{r}
########################################################################
# Function: GraphAnova
# Graphs box plot with whiskers 
# Input: continuous numeric vector for x and discrete vector for y
# Output: box plot with whiskers and F value

GraphAnova <- function(data=cbind(runif(10),runif(10))) {
  x <- data[,1]
  y <- data[,2]
  dataFrame <- data.frame(x,y)

 AnovaModel<- aov(y~x,data=dataFrame)
  
  
  return(boxplot(y~x,data=dataFrame,col=c("purple","limegreen","royalblue")))
}

GraphAnova(data1)
```


# Simulating data
```{r}
str(data1)
hist(data1[,2])
summary(data1[,2])
sd(data1[,2])
summary(data1[1:300,2])
sd(data[1:300,2])
summary(data1[301:600,2])
sd(data[301:600,2])

# we can use rnorm with this data

Column <- data1[,1]
Sporocysts <- round(c(rnorm(300,mean=140.4, sd=28.81225),rnorm(300,mean=144.0,sd=20.70705)))
head(Sporocysts)
randomData <- cbind.data.frame(Column,Sporocysts)
head(randomData)


# Now that we have simulated data with similar parameters to the actual data, we can see if we get comparable results when we run ANOVA on the simulated data.
AnovaData(randomData)
GraphAnova(randomData)


```

